//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("NokatModel", "FK_Votes_Jokes", "Jokes", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MyNokatMVC3.Models.Jokes), "Votes", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MyNokatMVC3.Models.Votes), true)]
[assembly: EdmRelationshipAttribute("NokatModel", "FK_Votes_Users", "Users", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MyNokatMVC3.Models.Users), "Votes", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MyNokatMVC3.Models.Votes), true)]

#endregion

namespace MyNokatMVC3.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class NokatModelContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new NokatModelContainer object using the connection string found in the 'NokatModelContainer' section of the application configuration file.
        /// </summary>
        public NokatModelContainer() : base("name=NokatModelContainer", "NokatModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NokatModelContainer object.
        /// </summary>
        public NokatModelContainer(string connectionString) : base(connectionString, "NokatModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new NokatModelContainer object.
        /// </summary>
        public NokatModelContainer(EntityConnection connection) : base(connection, "NokatModelContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Users> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<Users>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<Users> _Users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Jokes> Jokes
        {
            get
            {
                if ((_Jokes == null))
                {
                    _Jokes = base.CreateObjectSet<Jokes>("Jokes");
                }
                return _Jokes;
            }
        }
        private ObjectSet<Jokes> _Jokes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Votes> Votes
        {
            get
            {
                if ((_Votes == null))
                {
                    _Votes = base.CreateObjectSet<Votes>("Votes");
                }
                return _Votes;
            }
        }
        private ObjectSet<Votes> _Votes;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(Users users)
        {
            base.AddObject("Users", users);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Jokes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToJokes(Jokes jokes)
        {
            base.AddObject("Jokes", jokes);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Votes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVotes(Votes votes)
        {
            base.AddObject("Votes", votes);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NokatModel", Name="Jokes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Jokes : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Jokes object.
        /// </summary>
        /// <param name="jokeId">Initial value of the JokeId property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="joke">Initial value of the Joke property.</param>
        /// <param name="addDate">Initial value of the AddDate property.</param>
        public static Jokes CreateJokes(global::System.Int32 jokeId, global::System.Int32 userId, global::System.String joke, global::System.DateTime addDate)
        {
            Jokes jokes = new Jokes();
            jokes.JokeId = jokeId;
            jokes.UserId = userId;
            jokes.Joke = joke;
            jokes.AddDate = addDate;
            return jokes;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 JokeId
        {
            get
            {
                return _JokeId;
            }
            set
            {
                if (_JokeId != value)
                {
                    OnJokeIdChanging(value);
                    ReportPropertyChanging("JokeId");
                    _JokeId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("JokeId");
                    OnJokeIdChanged();
                }
            }
        }
        private global::System.Int32 _JokeId;
        partial void OnJokeIdChanging(global::System.Int32 value);
        partial void OnJokeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Joke
        {
            get
            {
                return _Joke;
            }
            set
            {
                OnJokeChanging(value);
                ReportPropertyChanging("Joke");
                _Joke = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Joke");
                OnJokeChanged();
            }
        }
        private global::System.String _Joke;
        partial void OnJokeChanging(global::System.String value);
        partial void OnJokeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime AddDate
        {
            get
            {
                return _AddDate;
            }
            set
            {
                OnAddDateChanging(value);
                ReportPropertyChanging("AddDate");
                _AddDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AddDate");
                OnAddDateChanged();
            }
        }
        private global::System.DateTime _AddDate;
        partial void OnAddDateChanging(global::System.DateTime value);
        partial void OnAddDateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NokatModel", "FK_Votes_Jokes", "Votes")]
        public EntityCollection<Votes> Votes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Votes>("NokatModel.FK_Votes_Jokes", "Votes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Votes>("NokatModel.FK_Votes_Jokes", "Votes", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NokatModel", Name="Users")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Users : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Users object.
        /// </summary>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="facebookId">Initial value of the FacebookId property.</param>
        /// <param name="accessToken">Initial value of the AccessToken property.</param>
        /// <param name="expires">Initial value of the Expires property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Users CreateUsers(global::System.Int32 userId, global::System.Int64 facebookId, global::System.String accessToken, global::System.DateTime expires, global::System.String name)
        {
            Users users = new Users();
            users.UserId = userId;
            users.FacebookId = facebookId;
            users.AccessToken = accessToken;
            users.Expires = expires;
            users.Name = name;
            return users;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if (_UserId != value)
                {
                    OnUserIdChanging(value);
                    ReportPropertyChanging("UserId");
                    _UserId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserId");
                    OnUserIdChanged();
                }
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 FacebookId
        {
            get
            {
                return _FacebookId;
            }
            set
            {
                OnFacebookIdChanging(value);
                ReportPropertyChanging("FacebookId");
                _FacebookId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FacebookId");
                OnFacebookIdChanged();
            }
        }
        private global::System.Int64 _FacebookId;
        partial void OnFacebookIdChanging(global::System.Int64 value);
        partial void OnFacebookIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AccessToken
        {
            get
            {
                return _AccessToken;
            }
            set
            {
                OnAccessTokenChanging(value);
                ReportPropertyChanging("AccessToken");
                _AccessToken = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AccessToken");
                OnAccessTokenChanged();
            }
        }
        private global::System.String _AccessToken;
        partial void OnAccessTokenChanging(global::System.String value);
        partial void OnAccessTokenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Expires
        {
            get
            {
                return _Expires;
            }
            set
            {
                OnExpiresChanging(value);
                ReportPropertyChanging("Expires");
                _Expires = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Expires");
                OnExpiresChanged();
            }
        }
        private global::System.DateTime _Expires;
        partial void OnExpiresChanging(global::System.DateTime value);
        partial void OnExpiresChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NokatModel", "FK_Votes_Users", "Votes")]
        public EntityCollection<Votes> Votes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Votes>("NokatModel.FK_Votes_Users", "Votes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Votes>("NokatModel.FK_Votes_Users", "Votes", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="NokatModel", Name="Votes")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Votes : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Votes object.
        /// </summary>
        /// <param name="voteId">Initial value of the VoteId property.</param>
        /// <param name="jokeId">Initial value of the JokeId property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="voteType">Initial value of the VoteType property.</param>
        public static Votes CreateVotes(global::System.Int32 voteId, global::System.Int32 jokeId, global::System.Int32 userId, global::System.Boolean voteType)
        {
            Votes votes = new Votes();
            votes.VoteId = voteId;
            votes.JokeId = jokeId;
            votes.UserId = userId;
            votes.VoteType = voteType;
            return votes;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VoteId
        {
            get
            {
                return _VoteId;
            }
            set
            {
                if (_VoteId != value)
                {
                    OnVoteIdChanging(value);
                    ReportPropertyChanging("VoteId");
                    _VoteId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("VoteId");
                    OnVoteIdChanged();
                }
            }
        }
        private global::System.Int32 _VoteId;
        partial void OnVoteIdChanging(global::System.Int32 value);
        partial void OnVoteIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 JokeId
        {
            get
            {
                return _JokeId;
            }
            set
            {
                OnJokeIdChanging(value);
                ReportPropertyChanging("JokeId");
                _JokeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("JokeId");
                OnJokeIdChanged();
            }
        }
        private global::System.Int32 _JokeId;
        partial void OnJokeIdChanging(global::System.Int32 value);
        partial void OnJokeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean VoteType
        {
            get
            {
                return _VoteType;
            }
            set
            {
                OnVoteTypeChanging(value);
                ReportPropertyChanging("VoteType");
                _VoteType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VoteType");
                OnVoteTypeChanged();
            }
        }
        private global::System.Boolean _VoteType;
        partial void OnVoteTypeChanging(global::System.Boolean value);
        partial void OnVoteTypeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NokatModel", "FK_Votes_Jokes", "Jokes")]
        public Jokes Jokes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Jokes>("NokatModel.FK_Votes_Jokes", "Jokes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Jokes>("NokatModel.FK_Votes_Jokes", "Jokes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Jokes> JokesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Jokes>("NokatModel.FK_Votes_Jokes", "Jokes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Jokes>("NokatModel.FK_Votes_Jokes", "Jokes", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("NokatModel", "FK_Votes_Users", "Users")]
        public Users Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("NokatModel.FK_Votes_Users", "Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("NokatModel.FK_Votes_Users", "Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Users> UsersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Users>("NokatModel.FK_Votes_Users", "Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Users>("NokatModel.FK_Votes_Users", "Users", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
